### ISSUE TITLE
mode

### ISSUE THREAD

**Issue by CVUsers** [zhoujx4/DuReader-Checklist-BASELINE#1]

**Comment by CVUsers** [comment]
pretrained model 在哪:
model_name_or_path", default="/data/zhoujx/prev_trained_model/chinese_roberta_wwm_ext_pytorch这个
还有个：tokenizer = BertTokenizerFast.from_pretrained("/data/zhoujx/prev_trained_model/rbt3")
你给的网址里面很多，没找到哪个是，，，
可以给份网盘吗？

**Comment by zhoujx4** [comment]
你好，你上面列的两个都不是baseline用的模型，我用的是这个

**Comment by zhoujx4** [comment]
> pretrained model 在哪:
> model_name_or_path", default="/data/zhoujx/prev_trained_model/chinese_roberta_wwm_ext_pytorch这个
> 还有个：tokenizer = BertTokenizerFast.from_pretrained("/data/zhoujx/prev_trained_model/rbt3")
> 你给的网址里面很多，没找到哪个是，，，
> 可以给份网盘吗？

你好，baseline用的是macbert，下载链接在https://huggingface.co/hfl/chinese-macbert-base/tree/main

**Comment by zhoujx4** [comment]
> /data/zhoujx/prev_trained_model/chinese_roberta_wwm_ext_pyt

**Comment by zhoujx4** [comment]
> pretrained model 在哪:
> model_name_or_path", default="/data/zhoujx/prev_trained_model/chinese_roberta_wwm_ext_pytorch这个
> 还有个：tokenizer = BertTokenizerFast.from_pretrained("/data/zhoujx/prev_trained_model/rbt3")
> 你给的网址里面很多，没找到哪个是，，，
> 可以给份网盘吗？

不好意思，README写得不好，pretrained model 是没有push到github上的，因为太大了，你根据上方的链接下载到具体目录，然后model_name_or_path参数填你下载的模型文件目录即可
