### ISSUE TITLE
predict时内存溢出

### ISSUE THREAD

**Issue by JeremySun1224** [zhoujx4/DuReader-Checklist-BASELINE#4]
您好，我在predict的时候总是内存溢出，机器的显存是32G，内存32G。
参数的设置是这样的：
`python predict.py --max_len=512 --model_name_or_path='/home/aistudio/pretrained_model/roberta-large-wwm' --per_gpu_eval_batch_size=512 --output_dir="./output" --fine_tuning_model='/home/aistudio/lic2021/output/best_model.pkl'`
请问是什么原因呢？

**Comment by zhoujx4** [comment]
哦哦 你用的是large模型哦，那确实存在这个可能
可以把predict时候的batch_size调少，例如从per_gpu_eval_batch_size=512改成per_gpu_eval_batch_size=400




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhoujx4/DuReader-Checklist-BASELINE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月4日(星期二) 晚上10:02
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[zhoujx4/DuReader-Checklist-BASELINE] predict时内存溢出 (#4)





 
您好，我在predict的时候总是内存溢出，机器的显存是32G，内存32G。
 参数的设置是这样的：
 python predict.py --max_len=512 --model_name_or_path='/home/aistudio/pretrained_model/roberta-large-wwm' --per_gpu_eval_batch_size=512 --output_dir="./output" --fine_tuning_model='/home/aistudio/lic2021/output/best_model.pkl'

**Comment by JeremySun1224** [comment]
嗯嗯好，谢谢您的回复，问题解决了，很开心😋
